/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "secondary-fixed": "#e5e2e1",
        "primary-fixed": "#00aeef",
        "on-surface": "#1f1b10",
        "on-primary": "#ffffff",
        "on-background": "#1f1b10",
        "surface-bone": "#eaf6ff",
        "primary-container": "#00aeef",
        "inverse-on-surface": "#f9f0dd",
        "background": "#eaf6ff",
        "surface-dim": "#d9efff",
        "primary": "#00aeef",
        "on-tertiary-fixed-variant": "#004f54",
        "surface": "#eaf6ff",
        "inverse-surface": "#343024",
        "inverse-primary": "#00aeef",
        "on-tertiary-fixed": "#002022",
        "on-primary-container": "#ffffff",
        "tertiary-fixed-dim": "#00dbe8",
        "tech-gray-dark": "#1a1a1a",
        "stark-white": "#ffffff",
        "error": "#ba1a1a",
        "outline-muted": "#7b8794",
        "secondary-fixed-dim": "#c8c6c5",
        "industrial-yellow": "#00aeef",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#dbeafe",
        "on-secondary-container": "#7b8794",
        "surface-container-low": "#e0f2fe",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#7b8794",
        "outline": "#7b8794",
        "secondary-container": "#e2dfde",
        "surface-tint": "#00aeef",
        "surface-container-high": "#bae6fd",
        "tertiary": "#00696f",
        "surface-container": "#e0f2fe",
        "outline-variant": "#7b8794",
        "on-primary-fixed": "#ffffff",
        "on-tertiary-container": "#006a70",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#005577",
        "tertiary-fixed": "#79f5ff",
        "hazard-red": "#ff3b30",
        "surface-container-highest": "#7dd3fc",
        "primary-fixed-dim": "#00aeef",
        "on-secondary-fixed": "#1c1b1b",
        "secondary": "#7b8794",
        "tertiary-container": "#00f1ff",
        "surface-bright": "#eaf6ff",
        "on-surface-variant": "#7b8794"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "container-max": "1280px",
        "section-padding": "80px",
        "margin-mobile": "16px",
        "unit": "8px"
      },
      "fontFamily": {
        "headline-xl": ["Space Grotesk"],
        "status-code": ["Space Grotesk"],
        "body-lg": ["Space Grotesk"],
        "label-caps": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "body-md": ["Space Grotesk"],
        "headline-lg-mobile": ["Space Grotesk"],
        "price-display": ["Space Grotesk"]
      },
      "fontSize": {
        "headline-xl": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "status-code": ["10px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "price-display": ["24px", {"lineHeight": "1", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
